version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
      - aws cloudformation package --template-file Search Gateway/search-gateway.yaml --s3-bucket artifactbucket012425 --output-template-file Search Gateway/search.yaml

artifacts:
  type: zip
  files:
    - Search Gateway/search-gateway.yaml
    - Search Gateway/search.yaml
