version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - aws cloudformation package --template-file PDFtoTXT/pdftotxt.yaml --s3-bucket artifactbucket012425 --output-template-file PDFtoTXT/lambdaoutput.yaml

artifacts:
  type: zip
  files:
    - PDFtoTXT/pdftotxt.yaml
    - PDFtoTXT/lambdaoutput.yaml
